[package]
name = "lt"
version = "0.1.0"
authors = ["anrosent <anson.rosenthal@gmail.com>"]

[dependencies]
rand = "0.3"
getopts = "0.2"

[lib]
name = "lt"
path = "src/lib.rs"

[[bin]]
name = "lt-encoder"
path = "bin/encoder.rs"


[[bin]]
name = "lt-decoder"
path = "bin/decoder.rs"
